services:
  app:
    build: ./src
    container_name: app
    command: python bot.py
    ports:
      - 80:80
    volumes:
      - ./src:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=F2gLeMF89xjpD3Yf742WHL0BTmBu2yQR
      - POSTGRES_USER=admin
      - POSTGRES_DB=prod
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - ./pg_data:/var/lib/postgresql/data