services:
  app:
    build: ./src
    container_name: app
    command: python bot.py
    ports:
      - 80:80
    volumes:
      - ./src:/app
    depends_on:
      - postgres
      - redis
      - redis_timers

  postgres:
    image: postgres:14-alpine
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=prod
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - ./pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

  redis_timers:
    image: redis:latest
    # ports:
    #   - 6379:6379

  # mongodb:
  #   image: mongodb/mongodb-community-server:6.0-ubi8
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=georgiy
  #     - MONGO_INITDB_ROOT_PASSWORD=DwA76qxM9aw48srr1m718F9Vu4yZpR26
  #     - MONGO_INITDB_DATABASE=users
  #   ports:
  #     - 27017:27017
