services:
  app:
    build: ./src
    container_name: app
    command: python bot.py
    ports:
      - 80:80
    volumes:
      - ./src:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=F2gLeMF89xjpD3Yf742WHL0BTmBu2yQR
      - POSTGRES_USER=admin
      - POSTGRES_DB=prod
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - ./pg_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:latest
  #   command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
  #   environment:
  #     - REDIS_HOST_PASSWORD=ZdFAZ1fi1Fv64ESl1jQYSjFp9skrZ4PV
  #   ports:
  #     - 6379:6379

  # redis_timers:
  #   image: redis:latest

  # mongodb:
  #   image: mongodb/mongodb-community-server:6.0-ubi8
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=georgiy
  #     - MONGO_INITDB_ROOT_PASSWORD=DwA76qxM9aw48srr1m718F9Vu4yZpR26
  #     - MONGO_INITDB_DATABASE=users
  #   ports:
  #     - 27017:27017
